<a href="https://colab.research.google.com/github/animesharma3/Pytorch-Code-Snippets/blob/main/Pytorch_Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import torch
import numpy as np

In [8]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device=device)
my_tensor =  torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device=device, requires_grad=True)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [9]:
my_tensor.dtype

torch.float32

In [10]:
my_tensor.device

device(type='cuda', index=0)

In [11]:
my_tensor.shape

torch.Size([2, 3])

In [12]:
my_tensor.requires_grad

True

### Common Initialization methods

In [14]:
x = torch.empty(size=(3, 3)) # random initialization
x

tensor([[-1.9808e-01,  0.0000e+00,  4.0824e-40],
        [ 3.5733e-43,  5.3810e-42,  1.4586e-39],
        [-1.7738e+38,  3.5733e-43,  2.1366e-34]])

In [15]:
x = torch.zeros((3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
x = torch.rand((3,3)) # randomly initialized uniformly distributed values b/w 0 and 1
x

tensor([[0.5264, 0.9703, 0.2744],
        [0.5568, 0.4537, 0.5924],
        [0.4800, 0.0462, 0.9903]])

In [18]:
torch.ones((3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
torch.eye(5,5) # I - identity matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [21]:
torch.arange(start=0, end=5, step=1) # Similar to range function in python

tensor([0, 1, 2, 3, 4])

In [22]:
torch.linspace(start=0.1, end=1, steps=10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [23]:
torch.empty(size=(1,5)).normal_(mean=0, std=1)

tensor([[ 0.1404, -1.0999, -0.2311,  1.4156, -0.6765]])

In [25]:
torch.empty(size=(1,5)).uniform_(0,1)

tensor([[0.8591, 0.5091, 0.6769, 0.3255, 0.2056]])

In [28]:
torch.diag(torch.ones(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### Initialize and convert tensor to other types

In [42]:
tensor = torch.arange(4)
print(tensor) # int64
print(tensor.bool())
print(tensor.short()) # int16
print(tensor.long()) # int64
print(tensor.half()) # float16
print(tensor.float()) # float32
print(tensor.double()) # float64

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


### Array to Tensor Conversion and Vice-Versa

In [45]:
# Array to Tensor
np_array = np.zeros((5,5))
tensor = torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [47]:
# Tensor to Array
tensor.numpy()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Tensor Math and Comparison Operations

In [48]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

In [49]:
# Addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)
print(z1)

tensor([10., 10., 10.])


In [51]:
z2 = torch.add(x, y)
z2

tensor([10, 10, 10])

In [53]:
z = x+y
z

tensor([10, 10, 10])

In [54]:
# Substraction
z = x-y
z

tensor([-8, -6, -4])

In [55]:
# Division
z = torch.true_divide(x, y) # element-wise division for equal shape
z

tensor([0.1111, 0.2500, 0.4286])

In [57]:
# Inplace Operation
t = torch.zeros(3)
t.add_(x) # Method ending with '_' support inplace operation

tensor([1., 2., 3.])

In [58]:
t += x

In [60]:
# Exponentiation
z = x.pow(2) # element-wise exponentiation
z

tensor([1, 4, 9])

In [61]:
z = x**2

In [62]:
# Simple comparison
z = x > 0
z

tensor([True, True, True])

In [63]:
z = x < 0
z

tensor([False, False, False])

In [64]:
# Matrix Multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2) # 2x3
x3

tensor([[0.6305, 0.9396, 1.2783],
        [0.4877, 1.1401, 0.9172]])

In [65]:
x1.mm(x2)

tensor([[0.6305, 0.9396, 1.2783],
        [0.4877, 1.1401, 0.9172]])

In [66]:
# Matric Exponentiation
matrix_exp = torch.rand(5,5)
matrix_exp.matrix_power(3)

tensor([[5.0628, 4.7212, 2.4995, 5.7880, 4.6596],
        [6.0254, 5.4556, 2.9711, 6.6295, 5.3886],
        [4.2168, 3.7466, 2.2524, 4.6971, 4.0156],
        [4.0536, 3.5661, 1.7327, 4.5471, 3.4343],
        [5.7795, 5.5333, 2.8354, 6.3830, 5.4273]])

In [67]:
# Element wise multiplication
z = x * y
z

tensor([ 9, 16, 21])

In [68]:
# dot product
z = torch.dot(x, y)
z

tensor(46)

In [71]:
# Batch Matrix Multiplication
batch = 32
n = 10
m = 20
p = 30
tensor1 = torch.rand((batch, n, m)) # For 2-dim matrix we don't need batch multiplication
tensor2 = torch.rand((batch, m, p))
tensor1.shape

torch.Size([32, 10, 20])

In [72]:
out_bmm = torch.bmm(tensor1, tensor2) # (batch, n, p)
out_bmm.shape

torch.Size([32, 10, 30])

In [74]:
# Examples of Broadcasting
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))
# x2 vector would be substracted from each row of x1 - Broadcasting
z = x1-x2
z

tensor([[ 0.1018, -0.0492,  0.3831,  0.1678, -0.9249],
        [-0.4578, -0.7663,  0.5015, -0.3625, -0.5748],
        [-0.4873, -0.6242,  0.2896, -0.5054, -0.1817],
        [-0.5831, -0.3097,  0.6811,  0.3025, -0.0577],
        [-0.3783, -0.4016,  0.0087, -0.2952, -0.0689]])

### Other useful tensor operations

In [75]:
print(x)
sum_x = torch.sum(x, dim=0)
sum_x

tensor([1, 2, 3])


tensor(6)

In [77]:
values, indices = torch.max(x, dim=0)
print(values, indices)

tensor(3) tensor(2)


In [78]:
values, indices = torch.min(x, dim=0)
print(values, indices)

tensor(1) tensor(0)


In [80]:
abs_x = torch.abs(x)
abs_x

tensor([1, 2, 3])

In [82]:
z = torch.argmax(x, dim=0) # index of the max num
z

tensor(2)

In [83]:
z = torch.argmin(x, dim=0) # index of the min num
z

tensor(0)

In [84]:
mean_x = torch.mean(x.float(), dim=0)
mean_x

tensor(2.)

In [85]:
torch.eq(x, y)

tensor([False, False, False])

In [86]:
torch.sort(y, dim=0, descending=False)

torch.return_types.sort(values=tensor([7, 8, 9]), indices=tensor([2, 1, 0]))

In [90]:
z = torch.clamp(x, min=0)
z

tensor([1, 2, 3])

In [91]:
x = torch.tensor([1,0,1,1,1], dtype=torch.bool)
z = torch.any(x) 
z

tensor(True)

In [92]:
torch.all(x)

tensor(False)

### Tensor Indexing

In [93]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))
print(x[0].shape)

torch.Size([25])


In [94]:
print(x[:,0].shape) 

torch.Size([10])


In [96]:
print(x[2])
print(x[2, 0:10])

tensor([0.7093, 0.9545, 0.1232, 0.7449, 0.5935, 0.8971, 0.9360, 0.9675, 0.8942,
        0.8343, 0.2751, 0.7031, 0.1646, 0.1502, 0.5083, 0.9165, 0.5230, 0.1849,
        0.8711, 0.4265, 0.8372, 0.0672, 0.1810, 0.2234, 0.5227])
tensor([0.7093, 0.9545, 0.1232, 0.7449, 0.5935, 0.8971, 0.9360, 0.9675, 0.8942,
        0.8343])


In [97]:
x = torch.arange(10)
indices = [2,5,8]
x[indices]

tensor([2, 5, 8])

In [99]:
x = torch.rand((3, 5))
print(x)
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
print(x[rows, cols])

tensor([[0.9115, 0.8759, 0.3837, 0.1053, 0.2155],
        [0.7223, 0.9250, 0.2345, 0.3211, 0.4278],
        [0.0347, 0.8478, 0.4562, 0.1718, 0.1448]])
tensor([0.4278, 0.9115])


In [104]:
# More advanced Indexing
x = torch.arange(10)
print(x)
print(x[(x<2) | (x>8)])
print(x[(x<2) & (x>8)])
print(x[x.remainder(2) == 0])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 9])
tensor([], dtype=torch.int64)
tensor([0, 2, 4, 6, 8])


In [106]:
torch.where(x>5, x, x*2)

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

In [107]:
torch.tensor([0,0,1,2,2,1,2]).unique()

tensor([0, 1, 2])

In [108]:
x.ndimension()

1

In [109]:
x.numel()

10

### Tensor Reshaping

In [111]:
x = torch.arange(9)
print(x)
x_3x3 = x.view(3,3)
x_3x3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [112]:
x.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [113]:
y = x_3x3.t() # transpose

y

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [117]:
# y.view(9) -> error
y.contiguous().view(9)

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [122]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
print(torch.cat((x1, x2)))
print(torch.cat((x1, x2), dim=0))
print(torch.cat((x1, x2), dim=1))

tensor([[0.1810, 0.4565, 0.1024, 0.8986, 0.5079],
        [0.4806, 0.9415, 0.5616, 0.3182, 0.0272],
        [0.0529, 0.7298, 0.4502, 0.5088, 0.6198],
        [0.8539, 0.8132, 0.1898, 0.9330, 0.8443]])
tensor([[0.1810, 0.4565, 0.1024, 0.8986, 0.5079],
        [0.4806, 0.9415, 0.5616, 0.3182, 0.0272],
        [0.0529, 0.7298, 0.4502, 0.5088, 0.6198],
        [0.8539, 0.8132, 0.1898, 0.9330, 0.8443]])
tensor([[0.1810, 0.4565, 0.1024, 0.8986, 0.5079, 0.0529, 0.7298, 0.4502, 0.5088,
         0.6198],
        [0.4806, 0.9415, 0.5616, 0.3182, 0.0272, 0.8539, 0.8132, 0.1898, 0.9330,
         0.8443]])


In [123]:
z = x1.view(-1) # flatten the tensor
z

tensor([0.1810, 0.4565, 0.1024, 0.8986, 0.5079, 0.4806, 0.9415, 0.5616, 0.3182,
        0.0272])

In [125]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
z.shape

torch.Size([64, 10])

In [126]:
z = x.permute(0,2,1)
z.shape

torch.Size([64, 5, 2])

In [128]:
x = torch.arange(10) #-> [10]
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

torch.Size([1, 10])
torch.Size([10, 1])


In [139]:
print(torch.arange(10))
print(torch.arange(10).unsqueeze(0))
print(torch.arange(10).unsqueeze(1))
print(torch.arange(10).unsqueeze(0).unsqueeze(1))
print(torch.arange(10).unsqueeze(0).unsqueeze(1).squeeze(1))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
